# Trip and Vacation - Reise und Urlaub

-  die Reise - the trip
    -  Die WG will eine Reise machen. The WG (living community) wants to make a trip.
-  verreisen - to travel
    -  Sie möchten verreisen. - They want to travel.
-  der Reiseplan - the travel plan
    -  Sie machen einen Reiseplan. - They are maing a travel plan.
-  das Reiseziel - the destination
    -  Sie haben nock kein bestimmtes Reiseziel. - They don't have a specific destination.
-  der Urlaub - the vacation
    -  Sie planen ihren Urlaub. - They are planning their vacation.
-  der Urlaubsort - the vacation destination
    -  Es gibt schöne Urlaubsorte in Deutschland. - There are beautiful vacation destinations in Germany.
-  Urlaub nehmen - to take holidays
    -  Bobbi nimmt eine Woche Urlaub. - Bobbi is taking a week of holidays.
-  Urlaub haben - to have holidays
    -  Bobbi hat bald Urlaub. - Bobbi has soon holidays.
-  in der Urlaub fahren - to go on vacation
    -  Die WG fährt in den Urlaub nach Bayern. - The WG goes on vacation to Bavaria.
-  den Urlaub verbringen - to spend the vacation
    -  Sie vebringen ihren Urlaub in den Bergen. - They are spending their vacation in the mountains.
-  Urlaub machen - to take a vacation
    -  Sie machen eine Woche Urlaub - They are taking a one week vacation.
-  die Reise / den Urlaub vorbereiten - to prepare a trip / vacation
    -  Sie müssen die Reise / den Urlaub verbereiten. - They have to prepare the trip / vacation.
-  die Ferien - the school holidays
    -  In den Ferien fahren die Kinder zu ihren Gosseltern. - During the school holidays the children go to their grandparents.
